#+TITLE: Donate
#+OPTIONS: num:nil

* Why would you give me money?

I'm a high school student passionate about programming and [[https://www.gnu.org/philosophy/free-sw.html][Free Software]]. I also like writing about stuff (mostly about things that grind my gears or tutorials). I don't want to /have to/ work for corporations developing proprietary crapware. Every cent you send will be extremely helpful to sustain myself during University next year and to follow my dream of contributing to Free Software projects. I'll also release every personal project under the GPL to ensure your freedoms are respected.

* Where to donate?

I currently accept donations on Liberapay. If any other libre donation service opens up and you wish to support me there, send me an email, and I'll look into it.

\\

#+ATTR_HTML: :target _blank :class liberapay
[[https://liberapay.com/brown121407][Donate on Liberapay]]

\\

I have a [[https://www.paypal.me/brown121407][PayPal account]] if you wish to make a one-time donation.
