#+TITLE: Notebook
#+OPTIONS: num:nil

* <2020-01-08 Wed>

*IDEA:* Libre job board. Will detail the specs later, I have something in mind.

*IDEA:* Libre bug-bounty-like? platform for Guix feature requests and packages.

You can request a package to be added and add a sum of money to that request. Other people can supplement that sum with whatever amount they want. When a commit that adds whatever was requested comes in the master branch, a link to claim the sum that amounted to that moment is sent to the author's email address from the commit. If the sum isn't claimed in a month after the commit entered master, should the money go towards Guix?

Maybe make use of GNU Taler for this?

* <2019-12-27 Fri>

*IDEA:* Libre API for an always-updated list of cities and counties of a country.x

* <2019-12-26 Thu>

Fourth day in a row writing daily here. Org mode is a blessing for my will to write -- it makes the process so much more enjoyable. And the fact that I'm in the winter break and there's no f-ing school for three quarters of the day each day may be helping too.

