#+TITLE: NearlyFreeSpeech reflections
#+DATE: <2020-07-14 Tue>

This is a sort of follow up for [[file:2019-12-23-moving-to-nfs.org][this post]].

I've been hosting this website on [[https://www.nearlyfreespeech.net/][NearlyFreeSpeech]] since December 2019. I think
that's one of the best deals I've ever done in my life.

When I signed up I loaded my account with $5. Guess how much I have left now,
after more than half a year! $2.49.

Since this website is just static files generated by Emacs with Org mode[fn::By
the way, I updated my scripts since [[file:2019-12-18-org-mode-site.org][this post]], check them out on [[https://git.sr.ht/~brown121407/brown.121407.xyz][Sourcehut]].],
their hosting plan fits my needs perfectly. I didn't want my site to be on
GitHub or GitLab servers and if I ever wanted to play with a bit of server side
logic I could just drop in a PHP file and be done with it. NFS does all this for
a great price.

I confess that I would like my own VPS to play with, so I could self-host some
stuff (like a Nextcloud instance or maybe setup my own mail server), but I can't
really afford that right now. So that leaves me with NearlyFreeSpeech.

I never had any problems with their service. I really encourage you to check
them out if you want to have your own website with maybe a bit of server side
interactivity or custom domains.
